# ...
  # ...
    # ...
      # ...
class Bottles
  def verse(_)
    "99 bottles of milk on the wall, " +
    "99 bottles of milk.\n" +
    "Take one down and pass it around, " +
    "98 bottles of milk on the wall.\n"
  end
end
